### ISSUE TITLE
Argument is of wrong type, but no exception thrown

### ISSUE THREAD

**Issue by wlafrance** [DataAction/AdoNetCore.AseClient#106]
I have a bit of code (using dapper) that is executing a query against my database (ASE 12) - AdoNetCore.AseClient(0.13.1 via nuget). 

The sql has a where clause like this where r.reg_id = @reg_id

Now in the database the reg_id column is a type of numeric, length 6, Prec 18, Scale 0

In the code the @reg_id variable is a Int32 and I would expect an exception to occur when I call the async method query but it just never errors out...

QUESTION: Is there a setting/configuration I need to set in dapper or ADO Provider to get datatype errors to kick out exceptions?

Code below will work because I set the datatype to decimal, but for other team members I would like for an exception to get kicked out so they know what the issue is... Any ideas?

`public async Task<IEnumerable<CentersForRegIdResponse>> Handle(CentersForRegIdQuery request, CancellationToken cancellationToken)
    {
        StringBuilder sql = new StringBuilder();

        sql.Append(" SELECT c.ctr_id, RTRIM(LTRIM(c.ctr_shname)) AS ctr_shname, RTRIM(LTRIM(r.reg_name)) AS reg_name ");
        sql.Append(" FROM center c, ");
        sql.Append(" region r ");
        sql.Append(" WHERE c.jcc_active = 'Y' and c.reg_id = r.reg_id and r.reg_id = @reg_id ");
        sql.Append(" ORDER BY  c.ctr_shname ");

        string query = sql.ToString();

        // custom mapping
        _dapperTools.DapperCustomMapping<CentersForRegIdResponse>();

        try
        {

            using (IDbConnection dbConnection = _dapperTools._aseconnection)
            {
                // example get list of rows by args
                var arguments = new
                {
                    @reg_id = request.RegId
                };
                IEnumerable<CentersForRegIdResponse> allRows =
                     await dbConnection.QueryAsync<CentersForRegIdResponse>(query, arguments);
                return allRows;
            }
        }
        catch (Exception ex)
        {
            _dapperTools.ReportSqlError(_log, query, ex);
            return null;
        }

    }

 public class CentersForRegIdQuery : IRequest<IEnumerable<CentersForRegIdResponse>>
{
    public Decimal RegId { get; set; }
}`

**Comment by senseibaka** [comment]
Hi @wlafrance,

Correct me if I'm wrong but as I understand it, your issue boils down to the following?

* You have a `reg_id numeric(18,0)` column in your DB
* You're passing an `int` parameter to your query
* The numeric column is compared with the `int` parameter

---

If that's the case, this shouldn't result in a datatype error.

The reason is, ASE Server will do some implicit type conversion if possible.
[This ASE 16 docs page](http://infocenter.sybase.com/help/topic/com.sybase.infocenter.dc32300.1600/doc/html/san1390612414475.html) has some tables showing what conversions are allowed and which ones can be done implicitly (the ASE 12.5.1 page doesn't give such a table, but does indicate implicit conversion occurs).

In the above case, `int` can be safely implicitly converted to `numeric (18,0)`, so it would be safe to compare `reg_id` and `@reg_id`. Therefore, ASE Server wouldn't consider this to be a datatype error.

Also, `sp_helpconfig 'conversion'` returns a few results, but nothing that seems relevant. I don't think you can disable this functionality.

Cheers
