### ISSUE TITLE
AseInfoMessageEventHandler loses context with Table Results

### ISSUE THREAD

**Issue by driseley** [DataAction/AdoNetCore.AseClient#134]
**Describe the bug**
We use a stored procedure to produce a report.  The output of the report come from both `print` statements in the stored procedure and returned cursors.

The current implementation loses the context between the print statements and cursors.

**To Reproduce**
Create the following procedure:
```
CREATE PROCEDURE st_report_example AS
BEGIN

PRINT 'Report table 1'
select 'value1', 'value2'

PRINT 'Report table 2'
select 'value3', 'value4'
END
```

Execute this using an `AseCommand` with an `AseInfoMessageEventHandler` to capture the output.

The driver does not offer any way to reconcile the order of print statements to results sets.

**Expected behaviour**

The driver should offer a way to reconcile the order of print statements to results sets.

**Environment**
- .NET Core 2.1
- `AdoNetCore.AseClient` nuget package version 0.14.0

**Additional context**

The TDS stream does return the print statements and results sets in the correct order

I propose adding a new event that can be subscribed to by the client to allow them to be notified when a result cursor is returned, fired from the `DataReaderTokenHandler` when a `IFormatToken` is encountered.  This combined with the existing `InfoMessage` event would allow the order to be reconstituted.

In the example about you would then see:

```
InfoMessageEvent(Report table 1)
TableResultEvent
InfoMessageEvent(Report table 2)
TableResultEvent
```
Thus we would know that the first InfoMessageEvent had been fired before the first cursor and the second InfoMessageEvent had been fired before the second cursor.

I will put together a pull request for this.

Please let me know if you think this is the best way to tackle this issue, or if there is another approach that would work?

**Comment by c-j-hughes** [comment]
Hey @driseley,

Just to dig a little deeper into this. There is a change on master, but not yet in a release, which allows the data provider to return messages from the server to the calling code before all results are ready. It shouldn't by itself return the messages out of order as the underlying TDS response stream has the messages in order, interleaved with the data tokens.

To get it to return out of order, I think you have to `SET FLUSHMESSAGE ON` on the command. If this is set, then out of order is the expected behaviour. It defaults to `OFF` though. Can you confirm that you are seeing this behaviour with `SET FLUSHMESSAGE OFF`? I might be wrong about this, so would appreciate your views.

The goal of the project is to try to be a drop-in replacement for the SAP AseClient. Admittedly, we haven't been 100% true to this where we think they have made mistakes in their implementation, but introducing a new event, while being compatible, should only be done if we are introducing a behaviour that the SAP AseClient does not already support in another way.

So, we're open to your proposal, but would like to understand it more in the context of what the SAP AseClient does under the same circumstances.

**Comment by driseley** [comment]
Hi @c-j-hughes ,

Thanks for the feedback.

I'll rig up a test case and try it with the reference driver, 0.15.0 and master of this driver, with FLUSHMESSAGE on and off and report back on what I find with each case.

I'll also post my client code, in case I'm doing something silly client side!

**Comment by driseley** [comment]
Hi @c-j-hughes 

I have done the testing with the following stored procedure:

```sql
CREATE PROCEDURE st_report_example AS
BEGIN

PRINT 'Report Header'
PRINT 'Table 1 Header'
select 'value1', 'value2'
PRINT 'Table 2 Header'
select 'value3', 'value4'
PRINT 'Report Trailer'

END
```

And the following client code:
```cs
static void Main(string[] args)
{
	var connectionString = $"Data Source=localhost;Port=5000;Database=MYDB;Uid=guest;Pwd=guest";
	var output = new List<string>();
	var messageEventHandler = new AseInfoMessageEventHandler((sender, eventArgs) =>
	{
		foreach (AseError error in eventArgs.Errors)
		{
			output.Add(error.Message);
		}
	});
	using (var connection = new AseConnection(connectionString))
	{
		connection.Open();
		try
		{
			connection.InfoMessage += messageEventHandler;
			var sql = "st_report_example";
			AseCommand command = new AseCommand(sql, connection);
			using (AseDataReader dataReader = command.ExecuteReader())
			{
				WriteOutput("BEFORE RESULTS");

				int tableIndex = 0;
				while (dataReader.HasRows)
				{
					tableIndex++;
					WriteOutput($"BEFORE TABLE {tableIndex}");
					DataTable dataTable = new DataTable();
					dataTable.Load(dataReader);
					Console.WriteLine(dataTable.Rows[0].ItemArray[0].ToString() + "," + dataTable.Rows[0].ItemArray[1].ToString());
					WriteOutput($"AFTER TABLE {tableIndex}");
				}

				WriteOutput("AFTER RESULTS");
			}
		}
		finally
		{
			connection.InfoMessage -= messageEventHandler;
		}

		WriteOutput("END");
	}

	void WriteOutput(string stage)
	{
		Console.WriteLine($"=== BEGIN {stage} ===");
		output.ForEach(s => Console.WriteLine(s));
		output.Clear();
		Console.WriteLine($"=== END {stage} ===");
	}
}
```
I did the testing against a 15.7 DB.
`set flushmessage on` and `set flushmessage off` made no difference to any of the tests.

The result from the reference driver Sybase.AdoNet45.AseClient.dll ( v16-SP03-PL04 ) was as follows:

```
=== BEGIN BEFORE RESULTS ===
Report Header
Table 1 Header
=== END BEFORE RESULTS ===
=== BEGIN BEFORE TABLE 1 ===
=== END BEFORE TABLE 1 ===
value1,value2
=== BEGIN AFTER TABLE 1 ===
Table 2 Header
=== END AFTER TABLE 1 ===
=== BEGIN BEFORE TABLE 2 ===
=== END BEFORE TABLE 2 ===
value3,value4
=== BEGIN AFTER TABLE 2 ===
Report Trailer
=== END AFTER TABLE 2 ===
=== BEGIN AFTER RESULTS ===
=== END AFTER RESULTS ===
=== BEGIN END ===
=== END END ===
```
Without the positional debug - the report looks like:
```
Report Header
Table 1 Header
value1,value2
Table 2 Header
value3,value4
Report Trailer
```

**This is the result that we wanted**, and would like to achieve with your driver.

Testing with your driver both on the master branch and from the 0.14.0 tag was:

```
=== BEGIN BEFORE RESULTS ===
Report Header
Table 1 Header
Table 2 Header
Report Trailer
=== END BEFORE RESULTS ===
=== BEGIN BEFORE TABLE 1 ===
=== END BEFORE TABLE 1 ===
value1,value2
=== BEGIN AFTER TABLE 1 ===
=== END AFTER TABLE 1 ===
=== BEGIN BEFORE TABLE 2 ===
=== END BEFORE TABLE 2 ===
value3,value4
=== BEGIN AFTER TABLE 2 ===
=== END AFTER TABLE 2 ===
=== BEGIN AFTER RESULTS ===
=== END AFTER RESULTS ===
=== BEGIN END ===
=== END END ===
```

Without the positional debug - the report looks like:
```
Report Header
Table 1 Header
Table 2 Header
Report Trailer
value1,value2
value3,value4
```

As you can see the, message events all fire before the first result set is retrieved by the client.

Do you have any thoughts on the best way to proceed, based on the tests above?

Many thanks
Dave

**Comment by c-j-hughes** [comment]
Hmmm. I think `SET FLUSHMESSAGE [ON|OFF]` does work at the server level. If I put sleeps in a proc, the messages do come back ahead of the data, but as soon as I hit the first result set, then that and any other result sets, and any subsequent messages seem to get batched up and not flushed. So probably not even relevant to this scenario as it doesn't alter the order of the tokens coming back.

I think I can see what is happening though. As we process the tokens we receive from the server, we dispatch messages immediately, but queue data items until all of the data is ready to pass to the `AseDataReader`.

I did a change a while back, that allowed the `AseDataReader` to be returned before the data items were all in. I backed it out because it added some complexity and it didn't have any obvious advantages - I think that would have formed the foundation for fixing the issue you have reported. 

Essentially instead of passing the `AseDataReader` a list of `TableResult`, it gets passed a `BlockingCollection<TableResult>` and read methods block while there is more data pending.

I think if we restore that change, and then make the `AseDataReader` also dispatch the messages while it is being enumerated, then the order returned from the server can be preserved - which would fix your issue, and FWIW respect `SET FLUSHMESSAGE [ON|OFF]` all of the way through.
