### ISSUE TITLE
cp1251 encoding error

### ISSUE THREAD

**Issue by djbios** [DataAction/AdoNetCore.AseClient#139]
**Describe the bug**
My Sybase working in windows 1251 encoding. In Sybase it's called cp1251 http://infocenter.sybase.com/help/index.jsp?topic=/com.sybase.infocenter.dc00729.1500/html/errMessageAdvRes/BABFCDJC.htm 

**To Reproduce**
 If I declare it in connection string as cp1251, I will get an error from  `_environment.Encoding = CharsetMap[newCharset](); ` in EnvChangeTokenHandler. 

**Expected behavior**
Encoding will be applied correctly.

**Comment by senseibaka** [comment]
Hi @djbios, does [this wiki page](https://github.com/DataAction/AdoNetCore.AseClient/wiki/Add-custom-charset-support) help?

**Comment by djbios** [comment]
Yep, i've fixed it already by adding custom encoding provider. But it looks like a workaround.

**Comment by senseibaka** [comment]
That's because in a sense, it _is_ a workaround. In another sense, it's not (because as far as I can tell, this is the canonical way to add extra string encoding support to a .net core application).

Since .net core does not come with built-in support for legacy code pages, _someone_ must import the library.

I believe it shouldn't be the driver's responsibility to import the library, because for the general use-cases of this driver, it adds unnecessary bloat. Therefore, let those who use legacy code pages add it themselves. @c-j-hughes might argue differently.

**Comment by senseibaka** [comment]
Follow-up: perhaps we can provide a supplementary nuget package which does all this encoder set-up automatically? It looks to be possible via a static constructor, so that all the user would need to do is import the package.

**Comment by djbios** [comment]
> That's because in a sense, it _is_ a workaround. In another sense, it's not (because as far as I can tell, this is the canonical way to add extra string encoding support to a .net core application).
> 
> Since .net core does not come with built-in support for legacy code pages, _someone_ must import the library.
> 
> I believe it shouldn't be the driver's responsibility to import the library, because for the general use-cases of this driver, it adds unnecessary bloat. Therefore, let those who use legacy code pages add it themselves. @c-j-hughes might argue differently.

Not sure, that it's about library importing. It's just about the naming. 
What do we have:
1) To find out which encoding is used, you watching at the connection string ( in our case it's `Charset=cp1251;`) We should provide exactly "cp1251", because it's that Sybase wants.

2) When in EnvChangeTokenHandler.cs you trying to find charset, you can't, because in NetCore terms this encoding called "windows-1251".

3) The problim is in missunderstanding terms of Sybase and NetCore. Your library is adapter between Sybase and NetCore. So, I think that adoptation is the responsibility of adaptor :)

P.S.
 In EnvChangeTokenHandler.cs you already map some Sybase encoding names on NetCore:
```
 {"iso_1", () => Encoding.GetEncoding("ISO-8859-1")},
            {"iso 8859-1", () => Encoding.GetEncoding("ISO-8859-1")},
            {"iso88591", () => Encoding.GetEncoding("ISO-8859-1")},
            {"ascii_8", () => Encoding.ASCII},
            {"utf-8", () => Encoding.UTF8},
            {"utf8", () => Encoding.UTF8},
```

**Comment by senseibaka** [comment]
The problem is that out-of-the-box, .net core does not implement encodings beyond the following:
* `utf-16`, Unicode, 1200
* `utf-16BE`, Unicode (Big-Endian), 1201
* `utf-32`, Unicode (UTF-32), 12000
* `utf-32BE`, Unicode (UTF-32 Big-Endian), 12001
* `us-ascii`, US-ASCII, 20127
* `iso-8859-1`, Western European (ISO), 28591
* `utf-7`, Unicode (UTF-7), 65000
* `utf-8`, Unicode (UTF-8), 65001

Read this: https://docs.microsoft.com/en-us/dotnet/standard/base-types/character-encoding#platform-notes-net-core
Or run this in a fresh .net core project to see for yourself:
```
public class Program
    {
        public static void Main(string[] args)
        {
            Console.WriteLine("Available encodings:");
            foreach (var enc in Encoding.GetEncodings())
            {
                Console.WriteLine($"* {enc.Name}, {enc.DisplayName}, {enc.CodePage}");
            }
            Console.WriteLine("Tests:");
            TestEncoding("ascii");
            TestEncoding("utf-8");
            TestEncoding("utf-16");
            TestEncoding("windows-1251");
        }

        private static void TestEncoding(string name)
        {
            try
            {
                Encoding.GetEncoding(name);
                Console.WriteLine($"* [{name}]: PASS");
            }
            catch (Exception ex)
            {
                Console.WriteLine($"* [{name}]: FAIL - {ex.Message}");
            }
        }
    }
```

**Comment by djbios** [comment]
Didn't notice that, now I am agree.
