### ISSUE TITLE
Unsupported data type 0 when reading strings

### ISSUE THREAD

**Issue by exaera** [DataAction/AdoNetCore.AseClient#152]
Hi all,

Has anyone encountered an issue where reading any data from columns containing text results either in unsupported data, 0 row count or reader being closed?

We are using .NET Core 2.2 / ASP.NET Core with connection to Sybase 16 and all attempts to read strings from columns fail either by using ExecuteReader method or DataTables.

If reading any other column with data type other than ones containing strings it works without issues.

We tried using VARCHAR, NVARCHAR, CHAR, TEXT as the type and all attempts to read the data fail.

One of the exceptions generated is below, other attempts to read just close the reader or return 0 rows.

`System.NotSupportedException: Unsupported data type 0 (column: )
   at AdoNetCore.AseClient.Internal.FormatItem.ReadTypeInfo(FormatItem format, Stream stream, Encoding enc)
   at AdoNetCore.AseClient.Internal.FormatItem.ReadForParameter(Stream stream, Encoding enc, TokenType srcTokenType)
   at AdoNetCore.AseClient.Token.ParameterFormatCommonToken.Read(Stream stream, DbEnvironment env, IFormatToken previousFormatToken)
   at AdoNetCore.AseClient.Token.ParameterFormat2Token.Create(Stream stream, DbEnvironment env, IFormatToken previous)
   at AdoNetCore.AseClient.Internal.TokenReader.Read(TokenReceiveStream stream, DbEnvironment env)+MoveNext()
   at AdoNetCore.AseClient.Internal.InternalConnection.InternalExecuteQueryAsync(AseCommand command, AseTransaction transaction, TaskCompletionSource 1 readerSource, CommandBehavior behavior)
--- End of stack trace from previous location where exception was thrown ---
   at AdoNetCore.AseClient.Internal.InternalConnection.ExecuteReader(CommandBehavior behavior, AseCommand command, AseTransaction transaction)
   at AdoNetCore.AseClient.AseCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.FillInternal(DataSet dataset, DataTable[] datatables, Int32 startRecord, Int32 maxRecords, String srcTable, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable[] dataTables, Int32 startRecord, Int32 maxRecords, IDbCommand command, CommandBehavior behavior)
   at System.Data.Common.DbDataAdapter.Fill(DataTable dataTable)`

**Comment by senseibaka** [comment]
Hi @exaera, I haven't personally experienced this, sorry.

Can you provide a cut-down version of your SQL + code which reproduces the issue?

Thanks

**Comment by megacodear** [comment]
Hi, we have the same problem. In our case when we consult a table (Select * from TABLE) that contains varchar fields, it does not respond directly.
You could solve it? Could you please share how they solved it?
Thank you very much

**Comment by senseibaka** [comment]
Hi @megacodear, The issue-raiser did not get back to me with steps for reproduction, so there is no fix.

Can you provide more detailed steps for reproducing the issue? In particular, the following are helpful
* Database server version (also please confirm that it is ASE)
* Driver version
* Table schema
* Affected SQL query

Thanks

**Comment by megacodear** [comment]
Hi @senseibaka, first of all thank you very much for your response.

I was investigating a little more and the problem is generated even when I don't use any tables in the query.

For example, if I run the following query:

Select 1 as Number
Union
Select 2 as Number

It works correctly and returns 2 records.

But if I execute the following query:

Select '1' as Number
Union
Select '2' as Number

It does not return any records.

On the other hand, by consulting real tables, I could identify that the problem occurs when I incorporate some field of type VARCHAR in the query.
That is, if I only check number fields, it works fine and returns the records normally. But if I include any field of type VARCHAR it does not work until it cancels by timeout.

I enabled the log, to write to a file, and I could identify that it is receiving unknown tokens. I copy the log detail:


FetchIdlePooledConnection found no idle connection
CreateNewPooledConnection start
InternalConnectionFactory.GetNewConnection start

----------  Send packet   ----------
Write TDS_BUF_LOGIN
Write TDS_CAPABILITY

---------- Receive Tokens ----------
TDS_ENVCHANGE: TDS_ENV_CHARSET -  -> utf8
TDS_ENVCHANGE: TDS_ENV_PACKSIZE - 512 -> 512
<- TDS_LOGINACK: TDS 5.0.0.0, SQL Anywhere 16.0.0
Login success
<- TDS_DONE: TDS_DONE_FINAL (799121)

----------  Send packet   ----------
Write TDS_BUF_NORMAL
Write TDS_LANGUAGE: 'USE base_prueba'

---------- Receive Tokens ----------
<- TDS_DONE: TDS_DONE_FINAL (0)

----------  Send packet   ----------
Write TDS_BUF_NORMAL
-> TDS_OPTIONCMD: TDS_OPT_SET, TDS_OPT_TEXTSIZE,
 00
 80
 00
 00

---------- Receive Tokens ----------
<- TDS_DONE: TDS_DONE_FINAL (0)
TDS_DONE: TDS_DONE_FINAL

========== ExecuteReader  ==========
Transaction set: False

----------  Send packet   ----------
Write TDS_BUF_NORMAL
Write TDS_LANGUAGE: 'Select top 10 batchno	
,imsi	
from esquema_prueba.tabla_prueba
'

---------- Receive Tokens ----------
<- TDS_ROWFMT2
  <- batchno: TDS_NUMN (len: 6) (ut:10) (status:TDS_ROW_NULLALLOWED) (loc:) format names available: ColumnLabel [batchno], ColumnName [batchno], CatalogName [base_prueba], ParameterName [], SchemaName [esquema_prueba], TableName [tabla_prueba]
  <- imsi: TDS_VARCHAR (len: 30) (ut:2) (status:TDS_ROW_COLUMNSTATUS, TDS_ROW_NULLALLOWED) (loc:) format names available: ColumnLabel [imsi], ColumnName [imsi], CatalogName [base_prueba], ParameterName [], SchemaName [esquema_prueba], TableName [tabla_prueba]
**Set new format token**
<- TDS_ROW
  <- batchno (12, 0)
!!! Hit unknown token type 15 !!!
!!! Hit unknown token type 55 !!!
!!! Hit unknown token type 51 !!!
!!! Hit unknown token type 49 !!!
!!! Hit unknown token type 49 !!!
!!! Hit unknown token type 53 !!!
!!! Hit unknown token type 48 !!!
!!! Hit unknown token type 57 !!!
!!! Hit unknown token type 8 !!!
!!! Hit unknown token type 55 !!!
!!! Hit unknown token type 0 !!!
!!! Hit unknown token type 15 !!!
!!! Hit unknown token type 55 !!!
!!! Hit unknown token type 51 !!!
!!! Hit unknown token type 49 !!!
!!! Hit unknown token type 48 !!!
!!! Hit unknown token type 53 !!!
!!! Hit unknown token type 55 !!!
<- TDS_ROW
  <- batchno (12, 0)
!!! Hit unknown token type 15 !!!
!!! Hit unknown token type 55 !!!
!!! Hit unknown token type 51 !!!
!!! Hit unknown token type 49 !!!
!!! Hit unknown token type 55 !!!
!!! Hit unknown token type 50 !!!
!!! Hit unknown token type 49 !!!
!!! Hit unknown token type 51 !!!
!!! Hit unknown token type 6 !!!
!!! Hit unknown token type 0 !!!
!!! Hit unknown token type 47 !!!
Released connection was placed in available queue


Thank you very much again for your help.

**Comment by senseibaka** [comment]
Thanks @megacodear for more info.

According to the logs the server identifies itself as "SQL Anywhere 16.0.0".
Unfortunately, we do not support this database -- this driver targets "Adaptive Server Enterprise" (ASE) versions 15/16.

Cheers

**Comment by megacodear** [comment]
Hi senseibaka, 

I understand, and that is a big problem for me.

Do you know any other open source driver that I can use to connect to SQL Anywhere?

Thank you very much for your help.

**Comment by senseibaka** [comment]
Hi @megacodear,

I have some suggestions, but I can't say for certain what's right as I have not ever interacted with SQL Anywhere...

1. ODBC - there is a nuget package for .net core apps which supports database communications via the ODBC protocol, it might work for you: https://www.nuget.org/packages/System.Data.Odbc/
2. It may be that jTDS supports SQL Anywhere, but this requires you to use Java.
3. It might be possible for you to implement necessary driver changes by either:
    - modifying this driver to add support, perhaps by auto-detecting the server type and switching a runtime flag. You can submit a PR if you'd like.
    - or, if that's too hard, forking/overhauling this codebase to make a separate driver could work too.

To implement 3, you'll need to find some way of capturing the bytes going back and forth, and maybe some documentation on how to interpret the bytes. You might find some luck in running the Ribo utility mentioned here [the Ribo utility mentioned here](https://github.com/DataAction/AdoNetCore.AseClient/wiki#suggested-dev-reference-material-for-contributers), but I don't know if SQL Anywhere comes with it...

Hope this helps

**Comment by megacodear** [comment]
Hi @senseibaka

Thank you very much for your suggestions and for your help. I will try them to solve my problem.

Thank you very much again.
