### ISSUE TITLE
[linq2db] NULL returned instead of byte[] { 0x00 }

### ISSUE THREAD

**Issue by MaceWindu** [DataAction/AdoNetCore.AseClient#57]
Test code:
```cs
Assert.That(conn.Execute<byte[]>("SELECT Cast(@p as binary(1))", DataParameter.Binary("p", new byte[0])), Is.EqualTo(new byte[] {0}));
```

linq2db test: 'SybaseTests.TestBinary'

**Comment by senseibaka** [comment]
Interesting; this sounds similar to the issue ASE has in determining if a string is null vs zero-length (the TDS spec makes no distinction). The way the reference driver gets around the string issue is to send a space character instead of a zero-length string.

I wonder if there's a similar behaviour for binary

**Comment by MaceWindu** [comment]
Can confirm it was fixed, now it fails another case from the same test. Will add new issue
