### ISSUE TITLE
Can data reader only handle a single table?

### ISSUE THREAD

**Issue by uchinago** [DataAction/AdoNetCore.AseClient#66]
I return multiple tables from a query...  but can not seem to be able to iterate over the tables.
Is there something I need to do to get the next table.   

Expect to be able to load each table returned into object then go to next table.

**Comment by senseibaka** [comment]
Hi @uchinago,

`AseDataReader` supports multiple tables; you can refer to [this test](https://github.com/DataAction/AdoNetCore.AseClient/blob/dadd02f2095adfd83466003451c2d63a09525f28/test/AdoNetCore.AseClient.Tests/Integration/AseDataReaderTests.cs#L914) to see how it's used.

Admittedly, we should have some more tests around this functionality.

If the above doesn't help, can you supply a code sample which demonstrates the problem?

Thanks

**Comment by senseibaka** [comment]
The closest test we have is [this one, for `connection.QueryMultiple`](https://github.com/DataAction/AdoNetCore.AseClient/blob/dadd02f2095adfd83466003451c2d63a09525f28/test/AdoNetCore.AseClient.Tests/Integration/EchoProcedureTests.cs#L119). None for `QueryMultipleAsync` -- I'll have a little play around and see if I can produce some errors/problems.

**Comment by senseibaka** [comment]
I've added a few tests in [this commit](https://github.com/DataAction/AdoNetCore.AseClient/commit/4efe4175126a9969a49133092480fc4646adc182), but no problems emerged.

In regards to Dapper's `.Read` - this is equivalent to calling `NextResult` (plus you get the data out if you want it).
In regards to the inability to select a `CommandBehavior`, this shouldn't interfere with your needs, because `CommandBehavior`'s `Default` behavior is to return all result sets.

**Comment by uchinago** [comment]
Outstanding.   I guess the standard driver doesn't close the reader so when I added the Using(var reader =)
It worked like a charm.  Thanks for all the help.
