### ISSUE TITLE
Add strong name to asembly to simplify provider consumption from projects with signing enabled

### ISSUE THREAD

**Issue by MaceWindu** [DataAction/AdoNetCore.AseClient#74]
I think title says it all :)

**Comment by senseibaka** [comment]
Agreed, it sounds like this won't cause any problems for consumers who don't strong-name, and will benefit those who do. I think our primary concern will be to ensure we store our private key securely.

**Comment by senseibaka** [comment]
As I was implementing this, I quickly discovered:
* Because we use `InternalsVisibleTo` to expose internal types to our test project, this necessitates the test projects being strongly-named, too.
* Because our test projects become strongly-named, we therefore require a strongly-named version of `Dapper`. Thankfully, `Dapper.StrongName` exists.

But, this concerned me, so I did some further reading, and I'm skeptical of the value of providing a strongly-named assembly. It seems to benefit some consumers at the expense of others. At the same time, I'm skeptical that the "benefit" is actually beneficial.

I also came across the blog posts which explain why things like `Dapper.StrongName` and `StackExchange.Redis.StrongName` exist, and I think we will follow their example:
* https://blog.marcgravell.com/2014/06/snk-we-need-to-talk.html
* https://blog.marcgravell.com/2014/07/snk-and-me-work-out-compromise.html

So, what I think we'll do is continue to provide `AdoNetCore.AseClient` in its current form, and publish an `AdoNetCore.AseClient.StrongName` package as well. [Here's the resulting commit (not yet PR'd)](https://github.com/senseibaka/AdoNetCore.AseClient/commit/17d49e2a8ce889b32d38416501def90c279010c5)
